# Generated by Django 3.0.3 on 2020-08-30 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('keyword1', models.CharField(max_length=50)),
                ('keyword2', models.CharField(max_length=50)),
                ('keyword3', models.CharField(max_length=50)),
                ('keyword4', models.CharField(max_length=50)),
                ('keyword5', models.CharField(max_length=50)),
                ('keyword6', models.CharField(max_length=50)),
                ('keyword7', models.CharField(max_length=50)),
                ('keyword8', models.CharField(max_length=50)),
                ('keyword9', models.CharField(max_length=50)),
                ('keyword10', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='podcast/thumbnails')),
                ('category1', models.CharField(max_length=50)),
                ('category2', models.CharField(max_length=50)),
                ('category3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='podcast/thumbnails')),
                ('length', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=10)),
                ('episode', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='podcast/files')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('explicit', models.CharField(default='NO', max_length=10)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast')),
            ],
        ),
    ]
