# Generated by Django 3.0.3 on 2020-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='creator',
            field=models.CharField(default='Leslie Caminade', max_length=100),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keyword9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
