# Generated by Django 3.0.3 on 2020-04-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail/%Y%m%d/'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='inlines/%Y%m%d/')),
                ('content_1', models.TextField(blank=True)),
                ('inline_1', models.ImageField(blank=True, upload_to='inlines/%Y%m%d/')),
                ('content_2', models.TextField(blank=True)),
                ('inline_2', models.ImageField(blank=True, upload_to='inlines/%Y%m%d/')),
                ('content_3', models.TextField(blank=True)),
                ('inline_3', models.ImageField(blank=True, upload_to='inlines/%Y%m%d/')),
                ('content_4', models.TextField(blank=True)),
                ('inline_4', models.ImageField(blank=True, upload_to='inlines/%Y%m%d/')),
                ('content_5', models.TextField(blank=True)),
                ('inline_5', models.ImageField(blank=True, upload_to='inlines/%Y%m%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
