# Generated by Django 3.0.3 on 2020-04-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200422_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='content_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='inline_1',
            field=models.ImageField(blank=True, upload_to='inlines/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='inline_2',
            field=models.ImageField(blank=True, upload_to='inlines/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='inline_3',
            field=models.ImageField(blank=True, upload_to='inlines/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='inline_4',
            field=models.ImageField(blank=True, upload_to='inlines/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='inline_5',
            field=models.ImageField(blank=True, upload_to='inlines/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='inlines/%Y%m%d/'),
        ),
    ]
