# Generated by Django 3.0.3 on 2020-04-22 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200422_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 6, 46, 22, 170754, tzinfo=utc)),
        ),
    ]
