# Generated by Django 3.0.3 on 2020-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200422_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='inline_1',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='inline_2',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='inline_3',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='inline_4',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='inline_5',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_1',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_2',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_3',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_4',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inline_5',
            field=models.ImageField(blank=True, upload_to='inlines/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail/'),
        ),
    ]
